name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Describe the problem you're trying to solve, not just the solution you want.
      placeholder: |
        My feature data lives in S3 and I have to download it locally before running timefence.
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed solution
      description: How do you think this should work?
      placeholder: |
        timefence.Source should accept s3:// paths directly since DuckDB supports them.
    validations:
      required: false

  - type: textarea
    id: workaround
    attributes:
      label: Current workaround
      description: How do you handle this today, if at all?
    validations:
      required: false

  - type: dropdown
    id: scope
    attributes:
      label: Does this fit Timefence's scope?
      description: "Timefence focuses on temporal correctness for ML training data. Features outside this scope are unlikely to be accepted."
      options:
        - "Yes - directly related to temporal correctness"
        - "Maybe - adjacent tooling (CLI, reporting, integrations)"
        - "Not sure"
    validations:
      required: true
